# ----
# Site

title: Institute for Biblical Content
url: https://ibc.oarc.science
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: A Bible society adhering to Open Access values
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: 
  links:


# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed: 
newsletter_action: 

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
    
    
monthsbel:
  January: "студзеня"
  February: "лютага"
  March: "сакавіка"
  April: "красавіка"
  May: "траўня"
  June: "чэрвеня"
  July: "ліпеня"
  August: "жніўня"
  September: "верасня"
  October: "красавіка"
  November: "лістапада"
  December: "снежня"  
